# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
      - main
      - convert-to-blazor
  paths:
    include:
      - azure-pipelines.yml

pool:
  vmImage: ubuntu-latest

variables:
  - name: rgName
    value: 'poc-knowledge-mining'
  - name: location
    value: 'westus2'
  - name: docsContainerName
    value: 'documents'
  - name: deploymentTemplate
    value: './deploy/infrastructure/env.bicep'

stages:
  - stage: infra
    displayName: Infrastructure
    jobs:
      - job: deploy
        displayName: "Deploy Infrastructure"
        steps:
          - task: AzureCLI@2
            displayName: 'Deploy Infra'
            name: deploy_infra
            inputs:
              azureSubscription: 'azure-knowledge-mining-arm-connection'
              scriptType: 'bash'
              scriptLocation: 'scriptPath'
              scriptPath: './scripts/deploy-infra.sh'
              arguments: '"$(location)" "$(rgName)" "$(deploymentTemplate)" "$(docsContainerName)" "$servicePrincipalId"'
              addSpnToEnvironment: true

  - stage: app
    displayName: App
    jobs:
      - job: build
        displayName: 'Build App and Skills'
        steps:
          - bash: "./scripts/publish-app.sh"
            displayName: "Publish App"

          - bash: "./scripts/publish-skills.sh"
            displayName: "Publish Skills"

          - publish: "./dist"
            displayName: "Publish artifacts"
            artifact: Dist

      - job: deploy
        displayName: 'Deploy App and Skills'
        variables:
          appName: $[stageDependencies.infra.deploy.outputs['deploy_infra.app_name']]
          skillsName: $[stageDependencies.infra.deploy.outputs['deploy_infra.skills_name']]
        steps:
          - download: current
            artifact: Dist
            displayName: "Download dist binaries"

          - task: AzureCLI@2
            displayName: "Deploy App"
            inputs:
              azureSubscription: 'azure-knowledge-mining-arm-connection'
              scriptType: 'bash'
              scriptLocation: 'scriptPath'
              scriptPath: './scripts/deploy-app.sh'
              arguments: '"$(rgName)" "$(appName)" "./dist/app.linux-x64.zip"'

          - task: AzureCLI@2
            displayName: "Deploy Skills"
            inputs:
              azureSubscription: 'azure-knowledge-mining-arm-connection'
              scriptType: 'bash'
              scriptLocation: 'scriptPath'
              scriptPath: './scripts/deploy-skills.sh'
              arguments: '"$(rgName)" "$(skillsName)" "./dist/skills.linux-x64.zip"'
            
  - stage: search
    displayName: 'Search'
    jobs:
      - job: deploy
        displayName: 'Configure Search'
        variables:
          keyVaultName: $[stageDependencies.infra.deploy.outputs['deploy_infra.keyvault_name']]
          storageAccountId: $[stageDependencies.infra.deploy.outputs['deploy_infra.storage_data_id']]
          searchEndpoint: $[stageDependencies.infra.deploy.outputs['deploy_infra.search_endpoint']]
          skillsName: $[stageDependencies.infra.deploy.outputs['deploy_infra.skills_name']]
        steps:
          - task: AzureKeyVault@1
            displayName: 'Get Secrets'
            inputs:
              azureSubscription: 'azure-knowledge-mining-arm-connection'
              KeyVaultName: '$(keyVaultName)'
              SecretsFilter: 'SEARCHSERVICESECRET,COGNITIVESERVICESSECRET,FUNCTIONADMINKEY'
              RunAsPreJob: false

          - task: AzureCLI@2
            displayName: 'Deploy Azure Search Configuration'
            inputs:
              azureSubscription: 'azure-knowledge-mining-arm-connection'
              scriptType: 'bash'
              scriptLocation: 'scriptPath'
              scriptPath: './scripts/deploy-search-config.sh' 
              arguments: '"./deploy/search-index" "$(storageAccountId)" "$(docsContainerName)" "$(searchEndpoint)" "$(SEARCHSERVICESECRET)" "$(COGNITIVESERVICESSECRET)" "$(skillsName)" "$(FUNCTIONADMINKEY)"' 
